### ISSUE TITLE
Failure to serialize lists

### ISSUE THREAD

**Issue by vetsin** [hiroaki-yamamoto/mongoengine-goodjson#26]
I have fields which may or may not be initialized which result in a thrown `KeyError` when serializing lists with version `1.0.1`

Both `MyDocument.objects[0].to_json()` and `MyDocument.objects[1].to_json()` will JSON encode as expected. However the following error occurs on trying to serialize both items:

```
>>> MyDocument.objects[0:1].to_json()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/<user>/.pyenv/versions/automation/lib/python2.7/site-packages/mongoengine_goodjson/queryset.py", line 80, in to_json
    lst = self.as_pymongo()
  File "/Users/<user>/.pyenv/versions/automation/lib/python2.7/site-packages/mongoengine_goodjson/queryset.py", line 70, in as_pymongo
    item[name] = self.__get_doc(fld, item[name])
KeyError: 'stopped_at'
```

Which is forcing a non-ideal workaround of
    `json.dumps([ json.loads(obj.to_json()) for obj in MyDocument.objects[0:1] ])`

**Comment by hiroaki-yamamoto** [comment]
Seems the doc has no `stopped_at` field, but `mongoengine.Document` can has the field that doesn't exist in the doc as `None`.

Wired. Do you mind if I ask you to provide the doc schema?

**Comment by vetsin** [comment]
This reproduced the error for me:

```
from mongoengine import *
import mongoengine_goodjson as gj
from datetime import datetime

connect(host='mongodb://<ip>:27017/test')

STATES = ('PENDING','SOMETHING')
class Scanner(gj.Document):
    session_name = StringField(required=True, unique=True)
    cid = StringField()
    zzz = StringField()
    xxx = StringField()
    yyy = StringField()
    state = StringField(choices=STATES, default=u'PENDING')
    created_at = DateTimeField(default=datetime.now)
    online_at = DateTimeField()
    started_at = DateTimeField()
    stopped_at = DateTimeField()
    scan_start = DateTimeField()
    scan_complete = DateTimeField()
    destroyed_at = DateTimeField()

s1 = Scanner(session_name='s1', online_at=datetime.now())
s1.save()

s2 = Scanner(session_name='s2', started_at=datetime.now())
s2.save()
```

Then

```
>>> Scanner.objects[0].to_json()
'{"created_at": "2017-04-03T09:45:55.926000", "session_name": "s1", "online_at": "2017-04-03T09:45:55.926000", "state": "PENDING", "id": "58e27c4407d32b9fd13f98b0"}'
>>> Scanner.objects[1].to_json()
'{"created_at": "2017-04-03T09:46:00.526000", "session_name": "s2", "started_at": "2017-04-03T09:46:00.526000", "state": "PENDING", "id": "58e27c4807d32b9fd13f98b1"}'
>>> Scanner.objects[0:1].to_json()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/<user>/.pyenv/versions/automation/lib/python2.7/site-packages/mongoengine_goodjson/queryset.py", line 80, in to_json
    lst = self.as_pymongo()
  File "/Users/<user>/.pyenv/versions/automation/lib/python2.7/site-packages/mongoengine_goodjson/queryset.py", line 70, in as_pymongo
    item[name] = self.__get_doc(fld, item[name])
KeyError: 'zzz'
```

**Comment by hiroaki-yamamoto** [comment]
Using array slice style, somehow `mongoengine.QuerySet` returns a list, but using `skip` and `limit`, I can see this bug.
