### ISSUE TITLE
Unexpected Error while saving Document in MongoEngine after using mongoengine-goodjson

### ISSUE THREAD

**Issue by ydvsailendar** [hiroaki-yamamoto/mongoengine-goodjson#267]
**Describe the bug**
I am not able to use the Model.from_json() method of mongoengine

**To Reproduce**
1. Install 

>  dnspython==2.1.0
>  mongoengine==0.22.1
>  mongoengine-goodjson==1.1.8

2. Code Model
```
import mongoengine as me
import mongoengine-goodjson as gj

class Person(gj.Document):
    first_name = me.StringField(min_length=3, max_length=15, required=True)
    middle_name = me.StringField(min_length=3, max_length=10)
    last_name = me.StringField(min_length=3, max_length=15, required=True)
    dob = me.DateField(required=True)
```
3. Code Function Lambda Serverless

```
from models.user.person import Person

def main(event, _):
    try:
        instance()
        person = Person.from_json(event["body"]).save().to_json()
    except Exception as err:
        print(err)
```
4. Run serverless offline and see the error
```
Traceback (most recent call last):
  File "/home/me/workspace/project/user-management/node_modules/serverless-offline/dist/lambda/handler-runner/python-runner/invoke.py", line 97, in <module>

    result = handler(input['event'], context)
  File "./functions/users/addPersonnelDetails.py", line 17, in main
    person = Person.from_json(event["body"]).save()
  File "/home/me/workspace/project/user-management/venv/lib/python3.8/site-packages/mongoengine_goodjson/document.py", line 342, in from_json
    valueDoc = value.as_doc()
AttributeError: 'NoneType' object has no attribute 'as_doc'
```

**Expected behavior**
Should have saved the document as expected since i was getting the expected response before adding this package.
I went through the documentation of mongoengine-goodjson and couldn't find any configurations. I am not sure if i am missing something or is a bug. 

**Desktop**
 - OS: [Ubuntu]
 - Browser [Chrome]
 - Version [ubuntu : 20.10. chrome: 87.0.4280.141]

**Comment by ydvsailendar** [comment]
looks liike you have mentioned that it overrides to_json and from_json so i guess it doesn't support any of them if i opt for this package.
