### ISSUE TITLE
Problem with empty list

### ISSUE THREAD

**Issue by derBroBro** [hiroaki-yamamoto/mongoengine-goodjson#76]
**Describe the bug**
If I have an empty list like `something = ListField(required=True, default=[""])` it is not possible to call to_json.
Used version: 1.1.5

```
Traceback (most recent call last):
  File "debug.py", line 10, in <module>
    print(r.to_json())
  File "C:\Python36\lib\site-packages\mongoengine_goodjson\document.py", line 222, in to_json
    use_db_field, cur_depth=current_depth, good_json=True
  File "C:\Python36\lib\site-packages\mongoengine_goodjson\document.py", line 160, in to_mongo
    self.begin_goodjson(cur_depth)
  File "C:\Python36\lib\site-packages\mongoengine_goodjson\document.py", line 148, in begin_goodjson
    self.__set_gj_flag_sub_field(name, fld, cur_depth=cur_depth)
  File "C:\Python36\lib\site-packages\mongoengine_goodjson\document.py", line 130, in __set_gj_flag_sub_field
    name, fld, cur_depth, set_good_json, "begin_goodjson"
  File "C:\Python36\lib\site-packages\mongoengine_goodjson\document.py", line 122, in __apply_element
    recursive_apply_flag(fld)
  File "C:\Python36\lib\functools.py", line 803, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "C:\Python36\lib\site-packages\mongoengine_goodjson\document.py", line 106, in set_flag_list
    recursive_apply_flag(fld.field)
  File "C:\Python36\lib\functools.py", line 803, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "C:\Python36\lib\site-packages\mongoengine_goodjson\document.py", line 102, in recursive_apply_flag
    func(fld, cur_depth)
  File "C:\Python36\lib\site-packages\mongoengine_goodjson\document.py", line 127, in set_good_json
    setattr(traget, "$$cur_depth$$", depth_lv)
AttributeError: 'NoneType' object has no attribute '$$cur_depth$$'
```

**To Reproduce**
```
class User(gj.Document):
    email = StringField(required=True)
    tags= ListField(required=True, default=[])

User.objects(pk=id).first().to_json()
```

**Expected behavior**
Get an empty list:
```
{
   "email": "foo@bar.local"
   "tags": []
}
```

I was able to fix this by checking ```unset_flag``` and ```set_flag``` for None. If wished I can open a PR for this.

**Comment by hiroaki-yamamoto** [comment]
@derBroBro Could you try ecd4f61? I think I fixed the problem, but I'm not sure this is the behavior you expect.

**Comment by hiroaki-yamamoto** [comment]
Ok. I will make a new release.

**Comment by derBroBro** [comment]
Awesome, thank you a lot!
